# Generated by Django 2.0.2 on 2018-04-09 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('dataNascimento', models.DateField()),
                ('dataMorte', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('isbn', models.IntegerField()),
                ('numero_paginas', models.IntegerField()),
                ('anoPublicacao', models.DateField(unique_for_year='year')),
                ('foto_capa', models.ImageField(upload_to='imagens')),
                ('autores', models.ManyToManyField(to='Livraria.Autor')),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Livraria.Editora')),
            ],
        ),
    ]
