# Generated by Django 2.0.2 on 2018-04-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livraria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='dataMorte',
            field=models.DateField(blank=True, null=True),
        ),
    ]
