# Generated by Django 2.0.2 on 2018-04-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livraria', '0002_auto_20180411_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='anoPublicacao',
            field=models.DateField(),
        ),
    ]
