# Generated by Django 2.0.2 on 2018-04-11 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Livraria', '0003_auto_20180411_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name_plural': 'Autores'},
        ),
    ]
